### ISSUE TITLE
Use `strtabs`

### ISSUE THREAD

**Issue by euantorano** [xmonader/nim-configparser#1]
I had a quick glance at your README, and noticed you're using a `Table[string, string]`:

```nim
type Section = ref object
    properties: Table[string, string]
```

Nim actually provides a [`strtabs`](https://nim-lang.org/docs/strtabs.html) module for this exact kind of task:

```nim
import strtabs

type Secion = ref object
  proprties: StringTableRef

proc newSection*() : Section =
  result = Section(
    properties: newStringTable(modeCaseInsensitive)
  )
```

**Comment by xmonader** [comment]
@euantorano Hi thanks for checking out the tutorial

I'm not sure if strtabs supports removing keys? I even tried setting the value to nil `lua removes keys by jut setting them to nil, but that didn't wrk too

**Comment by euantorano** [comment]
You are correct, I hadn't noticed that actually.
